"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["main.py"]
DATA_FILES = ["figure", "function", "sound_effect", "system", "text", "TaipeiSansTCBeta-Regular.ttf", "ntu.icns"]
PACKAGES = ["function", "system"]
RESOURCE = ["figure", "sound_effect", "text", "TaipeiSansTCBeta-Regular.ttf", "ntu.icns"]
OPTIONS = {
    'iconfile':'ntu.icns',
    'argv_emulation': True,
    'packages': PACKAGES,
    'resources': RESOURCE,
    }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)